---
- name: "Validate_ required parameters are defined"
  ansible.builtin.assert:
    that:
      - setup_radvd_baremetal_bridge is defined
      - setup_radvd_ipv6_network_cidr is defined

- name: "Validate_ values of interval and lifetime parameters are positive integers"
  ansible.builtin.assert:
    that:
      - setup_radvd_min_interval | int > 0
      - setup_radvd_max_interval | int > 0
      - setup_radvd_default_lifetime | int > 0

- name: "Validate_ for intervals, min < max"
  ansible.builtin.assert:
    that: setup_radvd_min_interval | int < setup_radvd_max_interval | int

- name: "Validate_ that setup_radvd_ipv6_network_cidr is a proper ipv6 network address"
  ansible.builtin.assert:
    that: setup_radvd_ipv6_network_cidr | ansible.utils.ipv6('network')
