---
- name: Check if network exists
  block:
    - name: Get network status
      community.libvirt.virt_net:
        name: "{{ network['name'] }}"
        command: status
      register: _snp_network_exists
      become: true
      tags:
        - cleanup
  rescue:
    - name: "Network not found — mark as absent"
      ansible.builtin.set_fact:
        _snp_network_exists:
          failed: true

- name: Stop SNO network
  community.libvirt.virt_net:
    command: destroy
    name: "{{ network['name'] }}"
  become: true
  failed_when: false
  when:
    - not _snp_network_exists.failed
  tags:
    - cleanup

- name: Undefine SNO network
  community.libvirt.virt_net:
    command: undefine
    name: "{{ network['name'] }}"
  become: true
  failed_when: false
  when:
    - not _snp_network_exists.failed
  tags:
    - cleanup
...
