---
- name: Validate_ cert_settings for container project
  ansible.builtin.assert:
    that:
      - cert_item.short_description is defined
      - cert_settings.auto_publish is defined
      - cert_settings.email_address is defined
      - cert_settings.build_categories is defined
      - cert_settings.registry_override_instruct is defined
      - cert_settings.application_categories is defined
      - cert_settings.os_content_type is defined
      - cert_settings.privileged is defined
      - cert_settings.release_category is defined
      - cert_settings.repository_description is defined
    success_msg: "All required cert_settings parameters are present"
  when: product_type == 'container'

- name: Validate_ cert_settings for operator project
  ansible.builtin.assert:
    that:
      - cert_item.short_description is defined
      - cert_settings.auto_publish is defined
      - cert_settings.email_address is defined
      - cert_settings.registry_override_instruct is defined
      - cert_settings.application_categories is defined
      - cert_settings.privileged is defined
      - cert_settings.repository_description is defined
    success_msg: "All required cert_settings parameters are present"
  when: product_type == 'operator'

- name: Validate_ cert_settings for Helm Chart project
  ansible.builtin.assert:
    that:
      - cert_item.short_description is defined
      - cert_settings.long_description is defined
      - cert_settings.email_address is defined
      - cert_settings.distribution_method is defined
      - cert_settings.application_categories is defined
      - cert_settings.distribution_instructions is defined
      - cert_settings.github_usernames is defined
    success_msg: "All required cert_settings parameters are present"
  when: product_type == 'helmchart'

- name: Validate_ Short Description Length
  ansible.builtin.assert:
    fail_msg: "The parameter cert_item.short_description is task is less 50 characters"
    success_msg: "The parameter cert_item.short_description is more than 50 characters"
    that: cert_item.short_description | length >= 50
...
