# Deploy a custom resource
#
# Required arguments:
#   api_version: The api version, including the namespace of the CR
#   (e.g hco.kubevirt.io/v1beta1)
#
#   namespace: The namespace in which the CR should be created
#
#   kind: The kind of the CR
#
#   name: The name that will be used to identify the CR
#
#   spec: The spec field of the CR.
---
- name: Deploy CR
  kubernetes.core.k8s:
    definition:
      apiVersion: "{{ dc_api_version }}"
      kind: "{{ dc_kind }}"
      metadata:
        name: "{{ dc_name }}"
        namespace: "{{ dc_namespace }}"
      spec: "{{ dc_spec }}"
  register: _deploy_cr_create_result
  retries: 5
  delay: 60
  until: _deploy_cr_create_result is not failed

- name: test_ Check that the CR is ready  # noqa: name[casing]
  kubernetes.core.k8s_info:
    api_version: "{{ dc_api_version }}"
    name: "{{ dc_name }}"
    namespace: "{{ dc_namespace }}"
    kind: "{{ dc_kind }}"
    wait: true
    wait_condition: "{{ dc_wait_condition }}"
    wait_timeout: "{{ dc_wait_timeout }}"
  register: _deploy_cr_result
  retries: "{{ dc_wait_retries }}"
  delay: "{{ dc_wait_delay }}"
  until: _deploy_cr_result is not failed
  when: dc_wait_for_cr | bool
...
