---
# defaults file for ocs-setup

### Local Storage Operator variables

# (Required) Channel versions to use, namespace and operators names
local_storage_operator: local-storage-operator
local_storage_namespace: openshift-local-storage

# (Required) Name of the LSO Storage Class
local_storage_class: localblock

# (Required) Type of LSO Volume Mode, either filesystem or block
local_volume_mode: block

# (Required) Replica size
replica_size: 3

### OCS Storage Operator variables

# (Required) Channel versions to use, namespace and operators names
ocs_storage_operator: ocs-operator
ocs_storage_namespace: openshift-storage

# (Optional) Whether to enable Multicloud Object Gateway (nooba)
enable_object_gateway: false

# (Required) default storageclass annotation
default_storageclass_annotation: '{"storageclass.kubernetes.io/is-default-class": "true"}'

# OCS gatherer_image
gatherer_image: registry.access.redhat.com/ubi8/ubi

# OpenShift Command Line Interface path
odf_setup_oc_tool_path: /usr/local/bin/oc

# ODF encryption support
odf_setup_enable_encryption: false
odf_setup_key_rotation_period: weekly

# ODF enable Ceph Tools
odf_setup_enable_ceph_tools: true

# CSI_PLUGIN_TOLERATIONS for rook-ceph-operator-config
odf_setup_csi_plugin_tolerations: |
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node.ocs.openshift.io/storage
    operator: Exists
    effect: NoSchedule

# ODF setup on control plane nodes. When true, add control-plane tolerations for LSO workloads.
odf_setup_ocs_on_control_plane: false
