---
- name: "Does node exist"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: status
  failed_when: false
  register: node_exists

- name: "Destroy network"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: destroy
  when: node_exists.status is defined

- name: "Undefine network"
  community.libvirt.virt_net:
    name: "{{ network['name'] }}"
    command: undefine
  when: node_exists.status is defined
