---
- name: "Validate_ parameters"
  ansible.builtin.assert:
    that:
      - fbc_bundles is defined
      - fbc_bundles | type_debug == "list"
      - fbc_index_image is defined
    fail_msg: "At least one of the parameters requirements is missing"

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    prefix: fbc_tmp_dir.
  register: fbc_tmp_dir

- name: "Set working directory"
  ansible.builtin.set_fact:
    fbc_tmp_dir: "{{ fbc_tmp_dir.path }}"

- name: "Set opm cmd"
  ansible.builtin.set_fact:
    fbc_opm_cmd: "{{ fbc_tmp_dir }}/opm-rhel{{ ansible_distribution_major_version }} {{ fbc_opm_args }}"

- name: Get ClusterVersion for opm download
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: _fbc_cluster_version
  failed_when: false

- name: "Download stable opm client"
  vars:
    _fbc_ver_query: "history[?state=='Completed'] | [0].version"
    _fbc_cv_status: "{{ (_fbc_cluster_version.resources | default([]) | first | default({})).status | default({}) }}"
    _fbc_full_ver: "{{ _fbc_cv_status | json_query(_fbc_ver_query) | default('', true) }}"
    _fbc_ocp_major: "{{ (_fbc_full_ver | default('4', true)).split('.')[0] }}"
    ocp_clients_url:
      "https://mirror.openshift.com/pub/openshift-v{{ _fbc_ocp_major }}/x86_64/clients/ocp/stable/\
      opm-linux{{ ansible_distribution_major_version is version('9', '==') | ternary('-rhel9', '') }}.tar.gz"
  ansible.builtin.unarchive:
    src: "{{ ocp_clients_url }}"
    dest: "{{ fbc_tmp_dir }}"
    remote_src: true
    mode: "0755"
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: "Create index build directory"
  ansible.builtin.file:
    path: "{{ fbc_tmp_dir }}/catalog"
    state: directory
    mode: "0755"

- name: "Build index image in temporary directory"
  ansible.builtin.include_tasks: add-bundle.yml
  loop: "{{ fbc_bundles }}"
  loop_control:
    loop_var: bundle
    label: "{{ bundle }}"

- name: "Validate_ catalog"
  ansible.builtin.command: |
    {{ fbc_opm_cmd }} validate catalog
  args:
    chdir: "{{ fbc_tmp_dir }}"
  register: catalog_validation
  retries: 6
  delay: 2
  until: not catalog_validation.failed

- name: "Add Dockerfile"
  ansible.builtin.template:
    src: catalog.Dockerfile.j2
    dest: "{{ fbc_tmp_dir }}/catalog.Dockerfile"
    mode: "0644"

- name: "Build the catalog"
  ansible.builtin.command: >
    podman build .
    --no-cache
    -f catalog.Dockerfile
    -t {{ fbc_index_image }}
  args:
    chdir: "{{ fbc_tmp_dir }}"

- name: "Delete temp directory"
  ansible.builtin.file:
    state: absent
    path: "{{ fbc_tmp_dir }}"

- name: "Display fbc_index_image"
  ansible.builtin.debug:
    msg: "Catalog image build as {{ fbc_index_image }}"
...
