#!/usr/bin/env bash
#
# Copyright (C) 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -e

BASEDIR=/usr/share/dci-pipeline
GITHUB_JOBNAME="DCI / DCI Job"

. "$BASEDIR/common"

URL="$1"

GITHUB_REPO_TOKEN=$($BASEDIR/get-config-entry "https://github.com/$proj" github_token "$GITHUB_TOKEN")

if [ -n "$GITHUB_REPO_TOKEN" ]; then
   AUTH=(-H "Authorization: token $GITHUB_REPO_TOKEN")
else
   AUTH=()
fi

pr=$(sed -e 's@.*/pull/'@@ <<< $URL)
proj=$(sed -e 's@https://github.com/\(.*\)/pull/.*@\1@i' <<< $URL)

if curl -s -L -H "Accept: application/vnd.github+json" "${AUTH[@]}" "https://api.github.com/repos/$proj/pulls/$pr/files"|jq -r .[].filename|grep -v '\.md$'|grep -E 'roles/|plugins/'; then
    dci-check-change --silent "$URL"
else
    json=$(curl -s -H "Accept: application/vnd.github.v3+json" "${AUTH[@]}" https://api.github.com/repos/$proj/pulls/$pr)
    STATUSES_URL=$(jq -r .statuses_url <<< $json)
    curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $GITHUB_REPO_TOKEN" -X POST -d "{\"state\":\"success\",\"context\":\"$GITHUB_JOBNAME\",\"description\": \"non code files\"}" "$STATUSES_URL"
fi

exit 0

# maybe-dci-check-change ends here
