#!/bin/bash
#
# Copyright (C) 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

GITHUB_JOBNAME="DCI / DCI Job"

# shellcheck disable=SC1091
if [ -r /etc/dci-openshift-agent/config ]; then
    . /etc/dci-openshift-agent/config
fi

GH_HEADERS=(
    "Accept: application/vnd.github.v3+json"
    "Authorization: token ${GITHUB_TOKEN}"
)

send_status() {
    curl -s "${GH_HEADERS[@]/#/-H}" -X POST -d "{\"state\":\"$1\",\"context\":\"$GITHUB_JOBNAME\"}" "$STATUSES_URL"
}

set -x

send_status pending

if /usr/share/dci-openshift-agent/test-runner "$@"; then
    send_status success
    exit 0
else
    send_status failure
    exit 1
fi

# test-runner-wrapper ends here
