---
- name: Create SSH known_hosts directory for conserver
  become: true
  ansible.builtin.file:
    path: /var/lib/conserver/.ssh
    state: directory
    owner: "root"
    group: "root"
    mode: "0700"

- name: Copy dell-idrac-ssh.sh to /usr/local/bin
  become: true
  ansible.builtin.copy:
    dest: /usr/local/bin/dell-idrac-ssh
    src: dell-idrac-ssh.sh
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create Dell iDRAC conserver config for {{ conserver_cluster }}
  become: true
  ansible.builtin.template:
    dest: "/etc/conserver-dell-idrac-{{ conserver_cluster }}.cf"
    src: conserver-dell-idrac.cf
    owner: "root"
    group: "root"
    mode: "0600"

- name: Add Dell iDRAC config include for {{ conserver_cluster }}
  become: true
  ansible.builtin.lineinfile:
    path: /etc/conserver.cf
    line: '#include /etc/conserver-dell-idrac-{{ conserver_cluster }}.cf'
