---
# tasks file for boot_disk

- name: Join list for workers and masters
  ansible.builtin.set_fact:
    boot_disk_hosts: "{{ groups['masters'] + groups['workers'] | default([]) }}"
  when: boot_disk_hosts is not defined

- name: Boot from disk for "{{ hostvars[item]['vendor'] }}"
  ansible.builtin.include_role:
    name: "redhatci.ocp.vendors.{{ hostvars[item]['vendor'] | lower }}"
    tasks_from: disk.yml
  vars:
    target_host: "{{ item }}"
  loop: "{{ boot_disk_hosts }}"
