---
- name: Merge and transform image mirrors to registries.conf format
  vars:
    combined_mirrors: |-
      {%- set c = dict() %}
      {%- for mirror in utils_image_mirrors %}
      {%- set s = mirror.source %}
      {%- set m = mirror.mirrors %}
      {%- if c.get(s) %}
      {%- set _ = c.update({s: (c[s] + m) | unique | list}) %}
      {%- else %}
      {%- set _ = c.update({s: m | list}) %}
      {%- endif %}
      {%- endfor %}
      {{ c }}
  ansible.builtin.set_fact:
    utils_acm_registries: |
      unqualified-search-registries = {{ utils_unqualified_search_registries }}
      short-name-mode = ""

      {% for registry in combined_mirrors.keys() | list %}
      [[registry]]
        prefix = ""
        location = "{{ registry }}"
        mirror-by-digest-only = true

      {% for mirror in combined_mirrors[registry] | unique | list %}
        [[registry.mirror]]
          location = "{{ mirror }}"

      {% endfor %}
      {% endfor %}
