# SPDX-License-Identifier: Apache-2.0
---
# defaults file for role redhatci.ocp.junit2json

# safeguard global variable:
global_json_reports_list: []

# defaults:
junit2json_input_merged_report: 'merged.junit.xml'
junit2json_output_merged_report: 'merged.junit.json'
junit2json_do_merge: true
