---
- name: Check required domain {item} exists
  ansible.builtin.command:
    cmd: "{{ required_binary }} {{ item.value }} A {{ item.value }} AAAA +short"
  register: res
  changed_when: false

- name: Check stdout for expected IP address
  ansible.builtin.set_fact:
    failed_domains: "{{ (failed_domains | default({})) | combine(\n    {\n        item.value: {\n            'stdout': res.stdout,\n            'stderr': res.stderr,\n\
      \            'expected': expected_answers[item.key],\n        }\n    }\n) }}"
  when: expected_answers[item.key] not in res.stdout
