---
- name: Unregister host via subscription-manager
  community.general.redhat_subscription:
    activationkey: "{{ activation_key }}"
    org_id: "{{ org_id }}"
    state: absent
  failed_when: false
  tags: unregister
