---
- name: Wait until NetworkAttachmentDefinition is created from SriovNetwork {{ sriov_conf.network.name }}
  kubernetes.core.k8s_info:
    api_version: k8s.cni.cncf.io/v1
    name: "{{ sriov_conf.network.name }}"
    namespace: "{{ sriov_conf.network.network_namespace | default('default') }}"
    kind: NetworkAttachmentDefinition
  register: net_attach_def_check
  retries: 6
  delay: 10
  until: net_attach_def_check.resources|length == 1
  no_log: true

# Some configurations applied in the SriovNetwork resources may imply a node reboot,
# handled by the SriovNetworkNodeState resources.
- name: Wait for SriovNetworkNodeState resources to be ready
  ansible.builtin.include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "SriovNetworkNodeState"  # noqa: redhat-ci[no-role-prefix]
    check_wait_retries: 30  # noqa: redhat-ci[no-role-prefix]
    check_wait_delay: 60  # noqa: redhat-ci[no-role-prefix]
