mabi_workarounds: []

mabi_generated_dir: "{{ repo_root_path }}/generated"
mabi_manifests_dir: "{{ mabi_generated_dir }}/{{ cluster_name }}"

mabi_bootstrap_node: "{{ groups.get('masters', [''])[0] }}"
mabi_host_ip_keyword: ansible_host
