---
- name: Create temporary directory for tooling
  ansible.builtin.tempfile:
    state: directory
    prefix: om_tmp.
  register: _om_tmp_dir

- name: Set permissions on temporary directory
  ansible.builtin.file:
    path: "{{ _om_tmp_dir.path }}"
    mode: "0700"

- name: Download stable oc-mirror and opm clients
  ansible.builtin.include_role:
    name: redhatci.ocp.ocp_tools
  vars:
    ot_tools:
      - oc-mirror
      - opm
    ot_dest: "{{ _om_tmp_dir.path }}"
    ot_delay: 60

- name: Download jq binary
  ansible.builtin.get_url:
    url: "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64"
    dest: "{{ _om_tmp_dir.path }}/jq"
    mode: "0755"
  register: _om_get_jq
  retries: 3
  delay: 60
  until: _om_get_jq is success
