---
- name: Create temporary directory for tooling
  ansible.builtin.tempfile:
    state: directory
    prefix: om_tmp.
  register: _om_tmp_dir

- name: Set permissions on temporary directory
  ansible.builtin.file:
    path: "{{ _om_tmp_dir.path }}"
    mode: "0700"

- name: Extract latest oc-mirror
  vars:
    tarball_name: "oc-mirror{{ ansible_distribution_major_version is version('9', '==') | ternary('.rhel9', '') }}.tar.gz"
  ansible.builtin.unarchive:
    src: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/{{ tarball_name }}"
    dest: "{{ _om_tmp_dir.path }}"
    remote_src: true
    mode: "0755"
  register: _om_get_oc_mirror
  retries: 3
  delay: 60
  until: _om_get_oc_mirror is success

- name: Download stable opm client
  vars:
    om_opm_rhel_url: >-
      https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/opm-linux-rhel{{ ansible_distribution_major_version }}.tar.gz
    om_opm_generic_url: >-
      https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/opm-linux.tar.gz
  block:
    - name: Check whether the RHEL-specific opm client is published
      ansible.builtin.uri:
        url: "{{ om_opm_rhel_url }}"
        method: HEAD
        status_code: [200, 404]
      register: _om_opm_rhel
      retries: 3
      delay: 10
      until: _om_opm_rhel.status | default(0) in [200, 404]

    - name: Download stable opm client
      vars:
        om_opm_url: >-
          {{
            (_om_opm_rhel.status | int == 200)
            | ternary(om_opm_rhel_url, om_opm_generic_url)
          }}
      ansible.builtin.unarchive:
        src: "{{ om_opm_url }}"
        dest: "{{ _om_tmp_dir.path }}"
        remote_src: true
        mode: "0755"
      register: _om_get_opm
      retries: 3
      delay: 10
      until: _om_get_opm is success

- name: Find the extracted opm binary
  ansible.builtin.find:
    paths: "{{ _om_tmp_dir.path }}"
    patterns: "opm*"
    file_type: file
  register: _om_opm_binaries

- name: Set opm binary path
  ansible.builtin.set_fact:
    om_opm_bin: "{{ _om_opm_binaries.files[0].path }}"

- name: Download jq binary
  ansible.builtin.get_url:
    url: "https://github.com/jqlang/jq/releases/download/jq-1.8.1/jq-linux-amd64"
    dest: "{{ _om_tmp_dir.path }}/jq"
    mode: "0755"
  register: _om_get_jq
  retries: 3
  delay: 60
  until: _om_get_jq is success
