---
- name: Ensure required variables are defined
  ansible.builtin.assert:
    that:
      - hostedbm_cluster_name is defined
      - hostedbm_cluster_base_domain is defined
      - hostedbm_guest_ingress_ip is defined
      - hostedbm_kubeconfig_file is defined

- name: Manage directories for deployment
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode | default(omit) }}"
    state: "{{ item.state }}"
  loop:
    - path: "{{ hostedbm_working_dir }}"
      state: absent
    - path: "{{ hostedbm_working_dir }}"
      state: directory
      mode: "0755"
    - path: "{{ hostedbm_out_dir }}"
      state: directory
      mode: "0755"
