---
- name: Create Minio deployment
  ansible.builtin.include_tasks: install.yml
  when:
    - sm_action == 'install'

- name: Create Minio deployment
  ansible.builtin.include_tasks: cleanup.yml
  when:
    - sm_action == 'cleanup'
...
