# SPDX-License-Identifier: Apache-2.0
---
# CI detection tasks for redhatci.ocp.test_report_send

- name: Recognize trs_ci_system as DCI
  ansible.builtin.set_fact:
    trs_ci_system: dci
  when:
    - trs_ci_system == "unknown"
    - lookup("env", "DCI_CS_URL") | length > 0

- name: Recognize trs_ci_system as GitHub
  ansible.builtin.set_fact:
    trs_ci_system: github
  when:
    - trs_ci_system == "unknown"
    - lookup("env", "GITHUB_API_URL") | length > 0

- name: Recognize trs_ci_system as GitLab
  ansible.builtin.set_fact:
    trs_ci_system: gitlab
  when:
    - trs_ci_system == "unknown"
    - lookup("env", "GITLAB_CI") | length > 0

- name: Recognize trs_ci_system as Jenkins
  ansible.builtin.set_fact:
    trs_ci_system: jenkins
  when:
    - trs_ci_system == "unknown"
    - lookup("env", "JENKINS_URL") | length > 0

- name: Recognize trs_ci_system as Prow
  ansible.builtin.set_fact:
    trs_ci_system: prow
  when:
    - trs_ci_system == "unknown"
    - lookup("env", "PROW_JOB_ID") | length > 0

- name: Validating trs_ci_system is supported
  ansible.builtin.assert:
    that: "{{ condition }}"
    fail_msg: "Assertion failed: {{ condition }}"
  loop:
    - trs_ci_system != "unknown"
    - trs_ci_system in trs_supported_ci_systems
  loop_control:
    loop_var: condition
