---
- name: Add user to libvirt group and get ssh key setup - {{ ansible_user }}
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: libvirt
    append: true
    state: present
    generate_ssh_key: true
  become: true
  tags: user
