---
- name: Generate random username if not provided
  ansible.builtin.set_fact:
    ss_username: >-
      {{ lookup('ansible.builtin.password', '/dev/null',
         length=16, chars=['ascii_letters', 'digits']) }}
    ss_credentials_generated: true
  when: ss_username is undefined or ss_username == ''
  no_log: true

- name: Generate random password if not provided
  ansible.builtin.set_fact:
    ss_password: >-
      {{ lookup('ansible.builtin.password', '/dev/null',
         length=32, chars=['ascii_letters', 'digits']) }}
    ss_credentials_generated: true
  when: ss_password is undefined or ss_password == ''
  no_log: true
