---
# tasks file for disconnected_registry
- name: Check required variables
  import_tasks: var_check.yml
  tags: create_registry

- name: Install prerequisites
  import_tasks: prerequisites.yml
  tags:
    - create_registry

- name: Set mirror registry certificate
  import_tasks: set_mirror_cert.yml

- name: Set up the mirror registry
  import_tasks: setup_registry.yml
  tags: create_registry

- name: Retrieve registry configuration
  import_tasks: retrieve_config.yml
  tags:
    - copy_config
