# SPDX-License-Identifier: Apache-2.0
---
# tasks file for redhatci.ocp.junit2json
# task list: convert.yml converts xml into JSON

- name: Read file content
  ansible.builtin.set_fact:
    junit2json_xml_report_content: "{{ lookup('ansible.builtin.file', item) }}"

- name: Generate content hash from the content
  ansible.builtin.set_fact:
    junit2json_xml_report_hash_path: "{{ item }}.{{ junit2json_hash }}"
    junit2json_xml_report_hash_curr: "{{ junit2json_xml_report_content | ansible.builtin.hash(junit2json_hash) }}"

# debug only:
- name: Print curr XML report filename
  ansible.builtin.debug:
    msg:
      - "XML report path is: {{ item }}"
  when:
    - junit2json_debug

- name: Obtain info on previous content checksum file
  ansible.builtin.stat:
    path: "{{ junit2json_xml_report_hash_path }}"
    checksum_algorithm: "{{ junit2json_hash }}"
  register: _junit2json_old_hash_stat

- name: Update junit2json_result_data junit2json_do_merge=true
  ansible.builtin.set_fact:
    junit2json_result_data: "{{ _junit2json_merged_xml.stdout | redhatci.ocp.junit2obj | to_nice_json }}"
  when:
    - junit2json_do_merge

- name: Convert junit XML to JSON and save in junit2json_result_data
  ansible.builtin.set_fact:
    junit2json_result_data: "{{ junit2json_xml_report_content | redhatci.ocp.junit2obj | to_nice_json }}"
  when:
    - not(junit2json_do_merge)

- name: Setup JSON report file name
  ansible.builtin.set_fact:
    junit2json_json_report_path: "{{ item | basename | regex_replace('\\.xml$', '.json') if item.endswith('.xml') else item | basename + '.json' }}"

- name: Set junit2json_output_report_path
  ansible.builtin.set_fact:
    junit2json_output_report_path: "{{ junit2json_output_dir }}/{{ junit2json_output_merged_report if junit2json_do_merge else junit2json_json_report_path }}"

- name: Set junit2json_xml_report_hash_old
  ansible.builtin.set_fact:
    junit2json_xml_report_hash_old: "{{ _junit2json_old_hash_stat.stat.checksum if _junit2json_old_hash_stat.stat.exists else '' }}"

- name: Update output variable global_json_reports_list
  ansible.builtin.set_fact:
    global_json_reports_list: "{{ global_json_reports_list + [junit2json_output_report_path] }}"

- name: Ensure json data destination folder
  ansible.builtin.file:
    path: "{{ junit2json_output_dir }}"
    state: directory
    mode: '0755'
  when:
    - junit2json_xml_report_hash_curr != junit2json_xml_report_hash_old

- name: Write json data to destination
  ansible.builtin.copy:
    content: "{{ junit2json_result_data | ansible.builtin.from_json | to_nice_json }}"
    dest: "{{ junit2json_output_report_path }}"
    mode: '0644'
  when:
    - junit2json_xml_report_hash_curr != junit2json_xml_report_hash_old

- name: Write current hash to destination
  ansible.builtin.copy:
    content: "{{ junit2json_xml_report_hash_curr }}"
    dest: "{{ junit2json_xml_report_hash_path }}"
    mode: '0644'
  when:
    - junit2json_xml_report_hash_curr != junit2json_xml_report_hash_old
