---
- name: "Map SRIOV variables to generic runner"
  ansible.builtin.set_fact:
    eco_gotests_generic_features: "{{ eco_gotests_eco_test_features_sriov }}"
    eco_gotests_generic_run_labels: []
    eco_gotests_generic_skip_labels: []
    eco_gotests_generic_env:
      ECO_VERBOSE_LEVEL: "{{ eco_gotests_verbose_level }}"
      ECO_TEST_VERBOSE: "{{ eco_gotests_test_verbose | lower }}"
      ECO_TEST_LABELS: "{{ eco_gotests_sriov_labels }}"
      ECO_WORKER_LABEL: "{{ eco_gotests_worker_label }}"
      ECO_OCP_SRIOV_MCP_LABEL: "{{ eco_gotests_sriov_mcp_label }}"
      ECO_CNF_CORE_NET_CNF_MCP_LABEL: "{{ eco_gotests_worker_label }}"
      ECO_CNF_CORE_NET_SRIOV_INTERFACE_LIST: "{{ eco_gotests_sriov_interface_list }}"
      ECO_OCP_SRIOV_INTERFACE_LIST: "{{ eco_gotests_sriov_interface_list }}"
      ECO_CNF_CORE_NET_TEST_CONTAINER: "{{ eco_gotests_network_test_container }}"
      ECO_OCP_SRIOV_TEST_CONTAINER: "{{ eco_gotests_ocp_sriov_test_container }}"
      ECO_CNF_CORE_NET_DPDK_TEST_CONTAINER: "{{ eco_gotests_dpdk_test_container }}"
      ECO_CNF_CORE_NET_FRR_IMAGE: "{{ eco_gotests_frr_image }}"
    eco_gotests_generic_timeout: "{{ eco_gotests_sriov_timeout }}"

- name: "Run SRIOV tests via generic runner"
  ansible.builtin.include_tasks: generic.yml
