---
- name: Get ClusterVersion for client download
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: _ah_cluster_version
  failed_when: false

- name: Download stable openshift client
  vars:
    _ah_ver_query: "history[?state=='Completed'] | [0].version"
    _ah_cv_status: "{{ (_ah_cluster_version.resources | default([]) | first | default({})).status | default({}) }}"
    _ah_full_ver: "{{ _ah_cv_status | json_query(_ah_ver_query) | default('', true) }}"
    _ah_ocp_major: "{{ (_ah_full_ver | default('4', true)).split('.')[0] }}"
    ocp_client_url:
      "https://mirror.openshift.com/pub/openshift-v{{ _ah_ocp_major }}/\
      x86_64/clients/ocp/stable/openshift-client-linux-amd64-rhel\
      {{ ansible_distribution_major_version }}.tar.gz"
  ansible.builtin.unarchive:
    src: "{{ ocp_client_url }}"
    dest: "{{ ah_tmp_dir }}"
    remote_src: true
    mode: "0755"
    extra_opts:
      - oc
      - kubectl
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Get route for hcp-cli
  kubernetes.core.k8s_info:
    kind: Route
    name: hcp-cli-download
    namespace: multicluster-engine
  register: ah_route
  until: ah_route.resources | length
  retries: 10
  delay: 10

- name: Download hcp cli tarball, ignoring the certificate
  vars:
    ah_arch: amd64
  ansible.builtin.unarchive:
    src: "https://{{ ah_route.resources[0].spec.host }}/linux/{{ ah_arch }}/hcp.tar.gz"
    dest: "{{ ah_tmp_dir }}"
    mode: "0755"
    remote_src: true
    validate_certs: false
  register: result
  retries: 3
  delay: 10
  until: result is not failed

- name: Get hcp cli version
  ansible.builtin.shell:
    cmd: >
      {{ ah_tmp_dir }}/hcp version
  register: result
  changed_when: false

- name: Print hcp cli version
  ansible.builtin.debug:
    var: result.stdout

- name: Set hcp cli path
  ansible.builtin.set_fact:
    ah_hcp_cli_path: "{{ ah_tmp_dir }}/hcp"

- name: Set oc cli path
  ansible.builtin.set_fact:
    ah_oc_cli_path: "{{ ah_tmp_dir }}/oc"
